# Site settings
author: Ben Mauss
title: Technically Speaking
header-img: img/home-bg.png
email: ben.mauss@gmail.com
copyright_name: Ben Mauss
description: > # this means to ignore newlines until "baseurl:"
  A Data Science Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bmauss

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
